#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all, expects="1+"
---
spring:
  #@overlay/match missing_ok=True
  #@overlay/remove
  datasource: (this value is ignored)

  #@overlay/match missing_ok=True
  #@overlay/remove
  jpa: (this value is ignored)


